version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: .scripts/initial.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: .scripts/startme.sh
      timeout: 120
      runas: root