version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: .scripts/initial.sh
      runas: root
      timeout: 3600
  ApplicationStart:
    - location: .scripts/startme.sh
      timeout: 3600
      runas: root