---
version: 0.2

phases:
  install:
    commands:
      - echo "Installing tools..."
      - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && dpkg -i erlang-solutions_1.0_all.deb && rm -f erlang-solutions_1.0_all.deb
      - echo "deb http://binaries.erlang-solutions.com/ubuntu $(lsb_release -cs) contrib" > /etc/apt/sources.list.d/erlang-solutions.list
      - curl -sL https://deb.nodesource.com/setup_9.x | bash -
      - apt-get install -y --no-install-recommends erlang-dev erlang-parsetools erlang-xmerl elixir nodejs 
      - echo "Installing deps for your project..."
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
  pre_build:
    commands:
      - if [ "$CODEBUILD_INITIATOR" == "codepipeline/yojee-pipeline" ]; then printf "export DB_HOSTNAME=$PROD_DB_HOSTNAME\nexport DB_PASSWORD=$PROD_DB_PASSWORD" >> .scripts/middle.sh && sed -i 's/MIX_ENV=dev/MIX_ENV=prod/g' .scripts/env.sh; fi
      - docker run -p 5432:5432 -e POSTGRES_PASSWORD=d0ntt3ll -d postgres
      - export MIX_ENV=test
      - mix ecto.create
      - mix test
  post_build:
    commands:
      - . ./.scripts/middle.sh; printf "export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID\nexport AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY\nexport DB_HOSTNAME=$DB_HOSTNAME\nexport DB_PASSWORD=$DB_PASSWORD" >> .scripts/env.sh 
      - rm -rf ./_build ./deps ./.scripts/middle.sh
      - env
artifacts:
  files:
    - '**/*'
  discard-paths: no