---
version: 0.2

phases:
  install:
    commands:
      - echo "Installing tools..."
      - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && dpkg -i erlang-solutions_1.0_all.deb && rm -f erlang-solutions_1.0_all.deb
      - echo "deb http://binaries.erlang-solutions.com/ubuntu $(lsb_release -cs) contrib" > /etc/apt/sources.list.d/erlang-solutions.list
      - curl -sL https://deb.nodesource.com/setup_9.x | bash -
      - apt-get install -y --no-install-recommends erlang-dev erlang-parsetools erlang-xmerl elixir nodejs 
      - echo "Installing deps for your project..."
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
  pre_build:
    commands:
      - docker run -p 5432:5432 -e POSTGRES_PASSWORD=d0ntt3ll -d postgres
      - Mix=test mix ecto.create
      - Mix=test mix test
  post_build:
    commands:
      - echo "export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID" >> .scripts/env.sh && echo "export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> .scripts/env.sh      
      - zip -r yojee_chat_example.zip ./* ./.scripts/
artifacts:
  files:
    - yojee_chat_example.zip
  discard-paths: no