---
version: 0.2

phases:
  install:
    commands:
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
  pre_build:
    commands:
      - service docker start && docker run -p 5432:5432 -e POSTGRES_PASSWORD=d0ntt3ll -d postgres
      - mix test
  build:
    commands:
      - cd assets && npm install      
      - mix release.init
      - mix release
artifacts:
  files:
    - yojee_*.tar.gz
  discard-paths: yes
  base-directory: _build/*/rel/*/releases/*/